# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
baseSVD <- function(X) {
    .Call('_SSGL615_baseSVD', PACKAGE = 'SSGL615', X)
}

c_which <- function(groups, g) {
    .Call('_SSGL615_c_which', PACKAGE = 'SSGL615', groups, g)
}

c_crossprod <- function(X) {
    .Call('_SSGL615_c_crossprod', PACKAGE = 'SSGL615', X)
}

matrix_subset_idx_rcpp <- function(x, y) {
    .Call('_SSGL615_matrix_subset_idx_rcpp', PACKAGE = 'SSGL615', x, y)
}

#' @export
c_Xtilde <- function(Xstar, groups, G, n) {
    .Call('_SSGL615_c_Xtilde', PACKAGE = 'SSGL615', Xstar, groups, G, n)
}

#' @export
c_Xstar <- function(Xs) {
    .Call('_SSGL615_c_Xstar', PACKAGE = 'SSGL615', Xs)
}

c_which2 <- function(groups, g) {
    .Call('_SSGL615_c_which2', PACKAGE = 'SSGL615', groups, g)
}

c_which3 <- function(beta, active) {
    .Call('_SSGL615_c_which3', PACKAGE = 'SSGL615', beta, active)
}

matrix_subset_idx_rcpp2 <- function(x, y) {
    .Call('_SSGL615_matrix_subset_idx_rcpp2', PACKAGE = 'SSGL615', x, y)
}

which4 <- function(x, active) {
    .Call('_SSGL615_which4', PACKAGE = 'SSGL615', x, active)
}

vector_subset_idx_rcpp2 <- function(x, y) {
    .Call('_SSGL615_vector_subset_idx_rcpp2', PACKAGE = 'SSGL615', x, y)
}

update <- function(Y, Xtilde, groups, sigmasq, beta, intercept, lambda0_base, Z, theta, G, forceGroups) {
    .Call('_SSGL615_update', PACKAGE = 'SSGL615', Y, Xtilde, groups, sigmasq, beta, intercept, lambda0_base, Z, theta, G, forceGroups)
}

